title : Reclaim Your Domain - Jim Groom

markdown: kramdown

safe: true
lsi: false
pygments: true
auto: true

source: jim-groom-reclaim-your-domain
destination: jim-groom-reclaim-your-domain

permalink: /:categories/:year/:month/:day/:title 
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]

paginate: 10
paginate_path: "/blog/page:num"

production_url : http://jimgroom.reclaimyourdomain.org

BASE_PATH : http://jimgroom.reclaimyourdomain.org

archive_path: /archive.html
categories_path : /categories.html
tags_path : /tags.html
